// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlS0jvEaosFceRoTH3lW1A_hSoidp6Hes',
    appId: '1:487391582232:web:a9632cc8fe9584f5e34b6d',
    messagingSenderId: '487391582232',
    projectId: 'flashback-be4c6',
    authDomain: 'flashback-be4c6.firebaseapp.com',
    storageBucket: 'flashback-be4c6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAowU_cYiRe22bYf2B1M-bbR2cSZlwvGI',
    appId: '1:487391582232:android:abac4d25f46764dee34b6d',
    messagingSenderId: '487391582232',
    projectId: 'flashback-be4c6',
    storageBucket: 'flashback-be4c6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6fEDjrkQ4l9VFDD-GWCQpwo2af7OG7Lc',
    appId: '1:487391582232:ios:4da1f02a2dddf741e34b6d',
    messagingSenderId: '487391582232',
    projectId: 'flashback-be4c6',
    storageBucket: 'flashback-be4c6.firebasestorage.app',
    iosClientId: '487391582232-1fb087gtgvblabpieb9gt1uh0molrsas.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashback',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6fEDjrkQ4l9VFDD-GWCQpwo2af7OG7Lc',
    appId: '1:487391582232:ios:4da1f02a2dddf741e34b6d',
    messagingSenderId: '487391582232',
    projectId: 'flashback-be4c6',
    storageBucket: 'flashback-be4c6.firebasestorage.app',
    iosClientId: '487391582232-1fb087gtgvblabpieb9gt1uh0molrsas.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashback',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlS0jvEaosFceRoTH3lW1A_hSoidp6Hes',
    appId: '1:487391582232:web:f853cc8328548695e34b6d',
    messagingSenderId: '487391582232',
    projectId: 'flashback-be4c6',
    authDomain: 'flashback-be4c6.firebaseapp.com',
    storageBucket: 'flashback-be4c6.firebasestorage.app',
  );
}
